public class RecruitmentConstants {
    public static final String VACANCY_STATUS_NEW = 'New';
    public static final String VACANCY_STATUS_IN_PROCESS = 'In-Process';
    public static final String VACANCY_STATUS_CENCELLED = 'Cancelled';
    public static final String VACANCY_STATUS_CLOSED = 'Closed';

    public static final String CANDIDATE_STATUS_NEW = 'New';
    public static final String CANDIDATE_STATUS_VALIDATED = 'Validated by HR';
    public static final String CANDIDATE_STATUS_DISCUALIFIED = 'Disqualified';
    public static final String CANDIDATE_STATUS_HIRED = 'Hired';
}
